// Code generated by Slice Machine. DO NOT EDIT.

import ArtStationLink from './ArtStationLink/index.svelte';
import CardList from './CardList/index.svelte';
import HeroText from './HeroText/index.svelte';
import ImageGallery from './ImageGallery/index.svelte';
import Spotlight from './Spotlight/index.svelte';
import TallImageGallery from './TallImageGallery/index.svelte';
import Title from './Title/index.svelte';

export const components = {
	art_station_link: ArtStationLink,
	card_list: CardList,
	hero_text: HeroText,
	image_gallery: ImageGallery,
	spotlight: Spotlight,
	tall_image_gallery: TallImageGallery,
	title: Title
};
