// Code generated by Slice Machine. DO NOT EDIT.

import CardList from './CardList/index.svelte';
import HeroText from './HeroText/index.svelte';
import Spotlight from './Spotlight/index.svelte';

export const components = {
	card_list: CardList,
	hero_text: HeroText,
	spotlight: Spotlight
};
